//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoDeClinica.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55868/ClinicaService.svc")]
        public string GerenciamentoDeClinica_localhost_ClinicaService {
            get {
                return ((string)(this["GerenciamentoDeClinica_localhost_ClinicaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data.xml")]
        public string SaveLocation {
            get {
                return ((string)(this["SaveLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data")]
        public string Root {
            get {
                return ((string)(this["Root"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data")]
        public string Root_XPath {
            get {
                return ((string)(this["Root_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pesquisar_medico")]
        public string Pesquisar_Medico {
            get {
                return ((string)(this["Pesquisar_Medico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_medico")]
        public string Pesquisar_Medico_XPath {
            get {
                return ((string)(this["Pesquisar_Medico_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pesquisar_crm")]
        public string Pesquisar_CRM {
            get {
                return ((string)(this["Pesquisar_CRM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_medico/pesquisar_crm")]
        public string Pesquisar_CRM_Nome {
            get {
                return ((string)(this["Pesquisar_CRM_Nome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("medicos_salvos")]
        public string Pesquisar_Medicos_Salvos {
            get {
                return ((string)(this["Pesquisar_Medicos_Salvos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_medico/medicos_salvos")]
        public string Pesquisar_Medicos_Salvos_XPath {
            get {
                return ((string)(this["Pesquisar_Medicos_Salvos_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medico")]
        public string Medico {
            get {
                return ((string)(this["Medico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_medico/Medico")]
        public string Pesquisar_Alterar_Medico {
            get {
                return ((string)(this["Pesquisar_Alterar_Medico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cadastrar_medico")]
        public string Cadastrar_Medico {
            get {
                return ((string)(this["Cadastrar_Medico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/cadastrar_medico")]
        public string Cadastrar_Medico_XPath {
            get {
                return ((string)(this["Cadastrar_Medico_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cadastrar_convenio")]
        public string Cadastrar_Convenio {
            get {
                return ((string)(this["Cadastrar_Convenio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/cadastrar_convenio")]
        public string Cadastrar_Convenio_XPath {
            get {
                return ((string)(this["Cadastrar_Convenio_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pesquisar_convenio")]
        public string Pesquisar_Convenio {
            get {
                return ((string)(this["Pesquisar_Convenio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_convenio")]
        public string Pesquisar_Convenio_XPath {
            get {
                return ((string)(this["Pesquisar_Convenio_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("convenios_salvos")]
        public string Pesquisar_Convenios_Salvos {
            get {
                return ((string)(this["Pesquisar_Convenios_Salvos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_convenio/convenios_salvos")]
        public string Pesquisar_Convenios_Salvos_XPath {
            get {
                return ((string)(this["Pesquisar_Convenios_Salvos_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Convenio")]
        public string Convenio {
            get {
                return ((string)(this["Convenio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paciente")]
        public string Paciente {
            get {
                return ((string)(this["Paciente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_paciente/Paciente")]
        public string Pesquisar_Alterar_Paciente {
            get {
                return ((string)(this["Pesquisar_Alterar_Paciente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cadastrar_paciente")]
        public string Cadastrar_Paciente {
            get {
                return ((string)(this["Cadastrar_Paciente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/cadastrar_paciente")]
        public string Cadastrar_Paciente_XPath {
            get {
                return ((string)(this["Cadastrar_Paciente_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pesquisar_paciente")]
        public string Pesquisar_Paciente {
            get {
                return ((string)(this["Pesquisar_Paciente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_paciente")]
        public string Pesquisar_Paciente_XPath {
            get {
                return ((string)(this["Pesquisar_Paciente_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pesquisar_cpf")]
        public string Pesquisar_CPF {
            get {
                return ((string)(this["Pesquisar_CPF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_paciente/pesquisar_cpf")]
        public string Pesquisar_CPF_Nome {
            get {
                return ((string)(this["Pesquisar_CPF_Nome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("paciente_salvos")]
        public string Pesquisar_Pacientes_Salvos {
            get {
                return ((string)(this["Pesquisar_Pacientes_Salvos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_paciente/paciente_salvos")]
        public string Pesquisar_Pacientes_Salvos_XPath {
            get {
                return ((string)(this["Pesquisar_Pacientes_Salvos_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Secretaria")]
        public string Secretaria {
            get {
                return ((string)(this["Secretaria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_secretaria/Secretaria")]
        public string Pesquisar_Alterar_Secretaria {
            get {
                return ((string)(this["Pesquisar_Alterar_Secretaria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cadastrar_secretaria")]
        public string Cadastrar_Secretaria {
            get {
                return ((string)(this["Cadastrar_Secretaria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/cadastrar_secretaria")]
        public string Cadastrar_Secretaria_XPath {
            get {
                return ((string)(this["Cadastrar_Secretaria_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pesquisar_secretaria")]
        public string Pesquisar_Secretaria {
            get {
                return ((string)(this["Pesquisar_Secretaria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_secretaria")]
        public string Pesquisar_Secretaria_XPath {
            get {
                return ((string)(this["Pesquisar_Secretaria_XPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pesquisar_cpf")]
        public string Pesquisar_Secretaria_CPF {
            get {
                return ((string)(this["Pesquisar_Secretaria_CPF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_secretaria/pesquisar_cpf")]
        public string Pesquisar_Secretaria_CPF_Nome {
            get {
                return ((string)(this["Pesquisar_Secretaria_CPF_Nome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("secretarias_salvas")]
        public string Pesquisar_Secretaria_Salvas {
            get {
                return ((string)(this["Pesquisar_Secretaria_Salvas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/pesquisar_secretaria/secretaria_salvas")]
        public string Pesquistar_Secretaria_Salvas_XPath {
            get {
                return ((string)(this["Pesquistar_Secretaria_Salvas_XPath"]));
            }
        }
    }
}
